name: 'LabVIEW Build Action'
description: 'Build LabVIEW project using CLI'

inputs:
  project-path:
    description: 'Path to LabVIEW project'
    required: true
  build-spec:
    description: 'Build specification name'
    required: true
  target:
    description: 'Target name for the build'
    required: false
    default: 'My Computer'
  version:
    description: 'Version to apply to the build'
    required: false
  build-type:
    description: 'File extension for the built artifact'
    required: false 
    default: 'nipkg'
outputs:
  artifact-path:
    description: 'Path to built exe file'
    value: ${{ steps.exec-buildspec.artifact.exe-path }}
runs:
  using: "composite"
  steps:
    - id: exec-buildspec
      run: |
        $args = @(
          "--project `"${{ inputs.project-path }}`""
          "--target `"${{ inputs.target }}`""
          "--buildspec `"${{ inputs.build-spec }}`""
          "--no-clean"
        )

        if ("${{ inputs.version }}" -ne "") {
          $args += "--version `"${{ inputs.version }}`""
        }

        $cmd = "g-cli --timeout 300000 lvbuildspec -- " + ($args -join " ")
        Write-Host "Running: $cmd"
        $output = Invoke-Expression $cmd
        Write-Host "GCLI raw output:"
        Write-Host $output

        $outPath = ($output -join "`n" | Select-String -Pattern "(.+\.${{ inputs.build-type }})" | ForEach-Object {
        $_.Matches[0].Groups[1].Value
        })
        Write-Host "Extracted artifact path: $outPath"

        "artifact-path=$outPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
      shell: powershell