name: 'LabVIEW Build Action'
description: 'Build LabVIEW project using CLI'

inputs:
  project-path:
    description: 'Path to LabVIEW project'
    required: true
  build-spec:
    description: 'Build specification name'
    required: true
  target:
    description: 'Target name for the build'
    required: false
    default: 'My Computer'
  version:
    description: 'Version to apply to the build'
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        $args = @(
          "--project", "${{ inputs.project-path }}"
          "--target", "${{ inputs.target }}"
          "--buildspec", "${{ inputs.build-spec }}"
          "--no-clean"
        )
        
        if ("${{ inputs.version }}") {
          $args += @("--version", "${{ inputs.version }}")
        }

        g-cli lvbuildspec @args
      shell: powershell