name: 'LUnit Test Action'
description: 'Runs all LUnit tests in LabVIEW project using LUnit CLI'

inputs:
  project-path:
    description: 'Path to LabVIEW project'
    required: true
  log-dir-path:
    description: 'Log output directory'
    required: false
    default: 'logs'

runs:
  using: "composite"
  steps:
      - run: if not exist "%GITHUB_WORKSPACE%\${{ inputs.log-dir-path }}" mkdir "%GITHUB_WORKSPACE%\${{ inputs.log-dir-path }}"
        shell: cmd
      - run: |
          g-cli lunit -- `
          --report "${{ inputs.log-dir-path }}\GCLI_LUnit.xml" `
          "${{ inputs.project-path }}"
        shell: powershell
      - name: Publish Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: LUnit Tests
          path: logs/GCLI_LUnit.xml
          reporter: java-junit