name: 'Close LabVIEW'
description: 'Closes the LabVIEW application'

inputs:
  path:
    description: 'Directory to mass comile'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        LabVIEWCLI `
          -OperationName MassCompile `
          -DirectoryToCompile "${{ github.workspace }}\${{ inputs.path }}" `
          -LabVIEWPath "$env:LabVIEWPath" `
          -PortNumber "$env:LabVIEWPort" `
          -LogToConsole true `
          -Verbosity Minimal `
          -Headless
      shell: powershell