name: 'LUnit Test Action'
description: 'Runs all LUnit tests in LabVIEW project using LUnit CLI'

inputs:
  project-path:
    description: 'Path to LabVIEW project'
    required: true
  ppl-path:
    description: 'Path to PPLs to use'
    required: true

runs:
  using: "composite"
  steps:
      - run: |
          $cmd = "LabVIEWCLI `
            -OperationName LinkToPPL `
            -ProjectPath "$env:GITHUB_WORKSPACE\${{ inputs.project-path }}" `
            -PPLPath "${{ inputs.ppl-path }}" `
            -LabVIEWPath $env:LabVIEWPath `
            -PortNumber $env:LabVIEWPort `
            -LogToConsole true `
            -Verbosity Minimal"
          Write-Host "Cmd:"
          Write-Host $cmd
          $output = Invoke-Expression $cmd
          Write-Host "Result:"
          Write-Host $output

        shell: powershell