name: 'LabVIEW Build Action'
description: 'Build LabVIEW project using CLI'

inputs:
  project-path:
    description: 'Path to LabVIEW project'
    required: true
  log-dir-path:
    description: 'Log output directory'
    required: false
    default: 'logs'

runs:
  using: "composite"
  steps:
      - run: |
          LabVIEWCLI `
            -OperationName LUnit `
            -ProjectPath "$env:GITHUB_WORKSPACE\${{ inputs.project-path }}" `
            -TestRunners 1 `
            -LabVIEWPath "$env:LabVIEWPath" `
            -PortNumber "$env:LabVIEWPort" `
            -LogFilePath "$env:GITHUB_WORKSPACE\${{ inputs.log-dir-path }}\LabVIEWCLI_LUnit.txt"
            -LogToConsole true `
            -Verbosity Diagnostic
