name: 'LabVIEW Build Action'
description: 'Build LabVIEW project using CLI'

inputs:
  project-path:
    description: 'Path to LabVIEW project'
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "Building LabVIEW project at ${{ inputs.project-path }}"
      shell: powershell