name: 'LUnit Test Action'
description: 'Runs all LUnit tests in LabVIEW project using LUnit CLI'

inputs:
  project-path:
    description: 'Path to LabVIEW project'
    required: true
  log-dir-path:
    description: 'Log output directory'
    required: false
    default: 'logs'
  fail-on-error:
    description: 'Fail build on failed test'
    required: false
    default: 'false'
  working-directory:
    description: 'Set working directory if not at root.'
    required: false
    default: ${{ github.workspace }}

runs:
  using: "composite"
  steps:
      - run: if not exist "%GITHUB_WORKSPACE%\${{ inputs.log-dir-path }}" mkdir "%GITHUB_WORKSPACE%\${{ inputs.log-dir-path }}"
        shell: cmd
      - run: |
          LabVIEWCLI `
            -OperationName LUnit `
            -ProjectPath "$env:GITHUB_WORKSPACE\${{ inputs.project-path }}" `
            -TestRunners 1 `
            -LabVIEWPath $env:LabVIEWPath `
            -PortNumber $env:LabVIEWPort `
            -ReportPath "${{ inputs.working-directory }}\${{ inputs.log-dir-path }}\LabVIEWCLI_LUnit.xml" `
            -LogToConsole true `
            -TestRunners 1 `
            -ClearIndex TRUE `
            -Verbosity Diagnostic
        shell: powershell
      - name: Publish Test Report
        uses: astemes/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: LUnit Tests
          path: ${{ inputs.working-directory }}\${{ inputs.log-dir-path }}\LabVIEWCLI_LUnit.xml
          reporter: java-junit
          fail-on-error: ${{ inputs.fail-on-error }}
          working-directory: ${{ inputs.working-directory }}