name: 'LUnit Test Action'
description: 'Runs all LUnit tests in LabVIEW project using LUnit CLI'

inputs:
  project-path:
    description: 'Path to LabVIEW project'
    required: true
  log-dir-path:
    description: 'Log output directory'
    required: false
    default: 'logs'

runs:
  using: "composite"
  steps:
      - run: if not exist "%GITHUB_WORKSPACE%\${{ inputs.log-dir-path }}" mkdir "%GITHUB_WORKSPACE%\${{ inputs.log-dir-path }}"
        shell: cmd
      - run: echo "$env:GITHUB_WORKSPACE\${{ inputs.log-dir-path }}\LabVIEWCLI_LUnit.xml"
        shell: powershell
      - run: |
          LabVIEWCLI `
            -OperationName LUnit `
            -ProjectPath "$env:GITHUB_WORKSPACE\${{ inputs.project-path }}" `
            -TestRunners 1 `
            -LabVIEWPath "$env:LabVIEWPath" `
            -PortNumber "$env:LabVIEWPort" `
            -ReportPath "$env:GITHUB_WORKSPACE\${{ inputs.log-dir-path }}\LabVIEWCLI_LUnit.xml" `
            -LogToConsole true `
            -LogFilePath c:\temp\lvlog.txt `
            -ClearIndex TRUE `
            -Verbosity Diagnostic
        shell: powershell
      - uses: dorny/test-reporter@v1
        if: always()
        with:
          name: LUnit Tests
          path: $env:GITHUB_WORKSPACE\${{ inputs.log-dir-path }}\*.xml
          reporter: java-junit