name: "Get Version"
description: "Extract version from a git tag (removes leading v)"

outputs:
  version:
    description: "The extracted version string"
    value: ${{ steps.extract_version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Extract version
      id: extract_version
      shell: powershell
      run: |
        $ref = "${{ github.ref_name }}"
        if ($ref -match '^v\d+\.\d+\.\d+$') {
          $version = $ref -replace '^v',''
        } else {
          $version = ""
        }
        Write-Host "Version is '$version'"
        "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append