name: "Get Version"
description: "Extract version from a git tag (removes leading v)"

inputs:
  tag:
    description: "The git tag (e.g. v1.2.3)"
    required: true

outputs:
  version:
    description: "The extracted version string"
    value: ${{ steps.extract_version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Extract version
      id: extract_version
      shell: powershell
      run: |
        $version = "${{ inputs.tag }}" -replace '^v',''
        Write-Host "Version is $version"
        "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append