name: Get Version

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  extract:
    runs-on: self-hosted
    steps:
      - name: Extract version from tag
        id: extract_version
        shell: powershell
        run: |
          $version = '${{ inputs.tag }}' -replace '^v',''
          Write-Host "Version is $version"
          "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
