name: Get Version

on:
  workflow_call:

jobs:
  extract:
    runs-on: self-hosted
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/')
        id: extract_version
        shell: powershell
        run: |
          $version = $env:GITHUB_REF -replace '^refs/tags/v',''
          Write-Host "Version is $version"
          "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
