name: "Release File"
description: "Publishes a file to a github release"

inputs:
  file-path:
    description: "Path to the file to release"
    required: true

runs:
  using: "composite"
  steps:
    - run: 'echo "${{ inputs.file-path }}"'
      shell: powershell
    - name: Release file
      uses: softprops/action-gh-release@v1
      if: github.ref_type == 'tag'
      with:
        tag_name: ${{ github.ref_name }}
        files: ${{ inputs.file-path }}
        prerelease: true