name: 'LabVIEW Build Action'
description: 'Build LabVIEW project using LabVIEW CLI'

inputs:
  project-path:
    description: 'Path to LabVIEW project'
    required: true
  build-spec:
    description: 'Build specification name'
    required: true
  target:
    description: 'Target name for the build'
    required: false
    default: 'My Computer'
  version:
    description: 'Version to apply to the build'
    required: false
  build-type:
    description: 'File extension for the built artifact'
    required: false 
    default: 'nipkg'
outputs:
  artifact-path:
    description: 'Path to built file'
    value: ${{ steps.exec-buildspec.outputs.artifact-path }}
runs:
  using: "composite"
  steps:
    - id: exec-buildspec
      run: |
        $args = @(
          "-OperationName ExecuteVersionedBuildSpec"
          "-ProjectPath `"$env:GITHUB_WORKSPACE\${{ inputs.project-path }}`""
          "-TargetName `"${{ inputs.target }}`""
          "-BuildSpecName `"${{ inputs.build-spec }}`""
          "-LabVIEWPath `"$env:LabVIEWPath`""
          "-PortNumber `"$env:LabVIEWPort`""
          "-LogToConsole true"
        )
        if ("${{ inputs.version }}" -ne "") {
          $args += "-Version `"${{ inputs.version }}`""
        }

        $cmd = "LabVIEWCLI " + ($args -join " ")
        Write-Host "Running: $cmd"
        $output = Invoke-Expression $cmd
        Write-Host "LabVIEWCLI raw output:"
        Write-Host $output
        $outPath = ($output -join "`n" | Select-String -Pattern "(.+\.${{ inputs.build-type }})" | ForEach-Object {
            $_.Matches[0].Groups[1].Value
        })
        Write-Host "Extracted artifact path: $outPath"

        "artifact-path=$outPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
      shell: powershell