name: 'LabVIEW Build Action'
description: 'Build LabVIEW project using CLI'

inputs:
  project-path:
    description: 'Path to LabVIEW project'
    required: true
  build-spec:
    description: 'Build specification name'
    required: true
  target:
    description: 'Target name for the build'
    required: false
    default: 'My Computer'
  port-number:
    description: 'Port number for LabVIEW CLI'
    required: false
    default: '3365'
  log-path:
    description: 'Path to store log files'
    required: false
    default: 'logs'

runs:
  using: "composite"
  steps:
    - run: |
        LabVIEWCLI `
          -OperationName ExecuteBuildSpec `
          -ProjectPath "$env:GITHUB_WORKSPACE\${{ inputs.project-path }}" `
          -TargetName "${{ inputs.target }}" `
          -BuildSpecName "${{ inputs.build-spec }}" `
          -PortNumber "${{ inputs.port-number }}" `
          -LogFilePath "$env:GITHUB_WORKSPACE\${{ inputs.log-path }}\LabVIEWCLI_ExecuteBuildSpec.txt" `
          -LogToConsole true `
          -Verbosity Minimal
      shell: powershell