name: 'LabVIEW Build Action'
description: 'Build LabVIEW project using CLI'

inputs:
  project-path:
    description: 'Path to LabVIEW project'
    required: true
  build-spec:
    description: 'Build specification name'
    required: true
  target:
    description: 'Target name for the build'
    required: false
    default: 'My Computer'

runs:
  using: "composite"
  steps:
    - run: |
        LabVIEWCLI `
          -OperationName ExecuteBuildSpec `
          -ProjectPath "$env:GITHUB_WORKSPACE\${{ inputs.project-path }}" `
          -TargetName "${{ inputs.target }}" `
          -BuildSpecName "${{ inputs.build-spec }}" `
          -LabVIEWPath "$env:LabVIEWPath" `
          -PortNumber "$env:LabVIEWPort" `
          -LogToConsole true `
          -Verbosity Diagnostic
      shell: powershell