name: 'LabVIEW Build Action'
description: 'Build LabVIEW project using CLI'
inputs:
  project-path:
    description: 'Path to LabVIEW project'
    required: true
  build-spec:
    description: 'Build specification name'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "Build project at ${{ inputs.project-path }} with spec ${{ inputs.build-spec }}"
      shell: pwsh
