name: 'LabVIEW Build Action'
description: 'Build LabVIEW project using CLI'

inputs:
  project-path:
    description: 'Path to LabVIEW project'
    required: true
  build-spec:
    description: 'Build specification name'
    required: true
  target:
    description: 'Target name for the build'
    required: false
    default: 'My Computer'
  port-number:
    description: 'Port number for LabVIEW CLI'
    required: false
    default: '3363'
  log-path:
    description: 'Path to store log files'
    required: false
    default: 'logs'

runs:
  using: "composite"
  steps:
    - run: echo "LabVIEWCLI `
          -OperationName ExecuteBuildSpec `
          -ProjectPath "$env:GITHUB_WORKSPACE\${{ inputs.project-path }}" `
          -TargetName "${{ inputs.target }}" `
          -BuildSpecName "${{ inputs.build-spec }}" `
          -PortNumber "${{ inputs.port-number }}" `
          -LogFilePath "$env:GITHUB_WORKSPACE\${{ inputs.log-path }}\LabVIEWCLI_ExecuteBuildSpec.txt" `
          -LogToConsole true `
          -Verbosity Minimal"
      shell: powershell
    - run: |
        LabVIEWCLI `
          -OperationName ExecuteBuildSpec `
          -ProjectPath "$env:GITHUB_WORKSPACE\${{ inputs.project-path }}" `
          -TargetName "${{ inputs.target }}" `
          -BuildSpecName "${{ inputs.build-spec }}" `
          -PortNumber "${{ inputs.port-number }}" `
          -LogFilePath "$env:GITHUB_WORKSPACE\${{ inputs.log-path }}\LabVIEWCLI_ExecuteBuildSpec.txt" `
          -LogToConsole true `
          -Verbosity Minimal
      shell: powershell


LabVIEWCLI -OperationName ExecuteBuildSpec -ProjectPath "C:\actions-runner\_work\danfoss-i10-i11-driver\danfoss-i10-i11-driver\TestStand\Projects\139Z9605\139Z9605.lvproj" -TargetName "My Computer" -BuildSpecName "Deployment" -PortNumber "3363" -LogToConsole true -Verbosity Minimal